#!/bin/sh

set -e

pgbouncer_version="$1"

if [ "$pgbouncer_version" == "" ]; then
  echo "usage: $0 VERSION"
  exit 1
fi

if [ "$AWS_ID" == "" ]; then
  echo "must set AWS_ID"
  exit 1
fi

if [ "$AWS_SECRET" == "" ]; then
  echo "must set AWS_SECRET"
  exit 1
fi

if [ "$S3_BUCKET" == "" ]; then
  echo "must set S3_BUCKET"
  exit 1
fi

basedir="$( cd -P "$( dirname "$0" )" && pwd )"

# make a temp directory
tempdir="$( mktemp -t pgbouncer_XXXX )"
rm -rf $tempdir
mkdir -p $tempdir
cd $tempdir

# build and package pgbouncer for heroku
vulcan build -v \
  -n pgbouncer \
  -c "cd pgbouncer-${pgbouncer_version} && curl -O https://gist.githubusercontent.com/anonymous/9593250/raw/f5cb325be4fec6058f184dfd48494e550c799bc4/patch && git apply patch && ./configure --prefix=/app/vendor/pgbouncer && make && make install" \
  -p /app/vendor/pgbouncer \
  -s http://pgfoundry.org/frs/download.php/3393/pgbouncer-${pgbouncer_version}.tar.gz \
  -o $tempdir/pgbouncer-${pgbouncer_version}.tgz

# upload pgbouncer to s3
$basedir/aws/s3 put $S3_BUCKET \
  pgbouncer-${pgbouncer_version}-heroku.tgz $tempdir/pgbouncer-${pgbouncer_version}.tgz

# generate manifest
$basedir/manifest pgbouncer
