#!/bin/sh

set -e

stunnel_version="$1"

if [ "$stunnel_version" == "" ]; then
  echo "usage: $0 VERSION"
  exit 1
fi

if [ "$AWS_ID" == "" ]; then
  echo "must set AWS_ID"
  exit 1
fi

if [ "$AWS_SECRET" == "" ]; then
  echo "must set AWS_SECRET"
  exit 1
fi

if [ "$S3_BUCKET" == "" ]; then
  echo "must set S3_BUCKET"
  exit 1
fi

basedir="$( cd -P "$( dirname "$0" )" && pwd )"

# make a temp directory
tempdir="$( mktemp -t stunnel_XXXX )"
rm -rf $tempdir
mkdir -p $tempdir
cd $tempdir

# build and package stunnel for heroku
vulcan build -v \
  -n stunnel \
  -c "cd stunnel-${stunnel_version} && ./configure --prefix=/app/vendor/stunnel && make; yes . | make install" \
  -p /app/vendor/stunnel \
  -s https://www.stunnel.org/downloads/stunnel-${stunnel_version}.tar.gz \
  -o $tempdir/stunnel-${stunnel_version}.tgz

# upload stunnel to s3
$basedir/aws/s3 put $S3_BUCKET \
  stunnel-${stunnel_version}.tgz $tempdir/stunnel-${stunnel_version}.tgz

# generate manifest
$basedir/manifest stunnel
