#!/bin/bash

set -e

PGBOUNCER_VERSION=${PGBOUNCER_VERSION-1.14.0}

pgbouncer_tarball_url=https://www.pgbouncer.org/downloads/files/${PGBOUNCER_VERSION}/pgbouncer-${PGBOUNCER_VERSION}.tar.gz

temp_dir=$(mktemp -d /tmp/pgbouncer.XXXXXXXXXX)

cd "$temp_dir"
echo "Temp dir: $temp_dir"

echo "Downloading $pgbouncer_tarball_url"
curl -L "$pgbouncer_tarball_url" | tar xzv

if [ -d "/buildpack/support/patchfiles/${PGBOUNCER_VERSION}" ]
then
		PATCHFILES=$(find /buildpack/support/patchfiles/"${PGBOUNCER_VERSION}" -name '*.patch')
else
		PATCHFILES=$(find /buildpack/support/patchfiles/default -name '*.patch')
fi

(
	cd pgbouncer-"${PGBOUNCER_VERSION}"
	for f in $PATCHFILES
	do
		patch -p0 < "$f"
	done

		./configure \
			--prefix=/tmp/pgbouncer
	make -j 2 install
)

tar -zcvf /buildpack/pgbouncer-"${STACK}".tgz -C /tmp/pgbouncer .
